### ISSUE TITLE
lists aren't converted well.

### ISSUE THREAD

**Issue by hrsma2i** [hashrock/md2sb-online#1]
I'm using a tab as an indent. It doesn't work.

**Comment by hashrock** [comment]
# sb2md

ScrapBoxではTab入力が可能なため、2スペースに置換してから変換を行うよう変更しました。

https://github.com/hashrock/md2sb-online/commit/d11803f37685532f1b76efa59945b7d268865410

# md2sb

MarkdownでのTab入力はエディタ側で対処可能のため、対応を予定しません。
