### ISSUE TITLE
The GitHub Pages version should show the new netlify url

### ISSUE THREAD

**Issue by kn1cht** [hashrock/md2sb-online#4]
いつもOnline ScrapBox Converterを便利に使わせていただいております．
[Netlifyに移転された](https://twitter.com/hashedrock/status/1243391785230950400)ということですが，元々のGitHub Pages版（https://hashrock.github.io/md2sb-online/ ）がjsの読み込みエラーで真っ白なページとして表示されるようになっています．

旧ページのリンクを辿った人がnetlify版にたどり着くのに苦労するかもしれないので，GitHub Pagesをnetlify版（https://md2sb-online.netlify.app/ ）に誘導するリンクまたはリダイレクトに置き換えてはいかがでしょうか？

**Comment by hashrock** [comment]
報告ありがとうございます。最近はGitHub PagesでもNetlifyとできることが遜色なくなってきているので、GitHub Pagesに再移転することで対処を考えています。リダイレクトはせず双方で引き続き動作させる想定です。

**Comment by kn1cht** [comment]
そうだったのですね、新しいGitHub Pages版楽しみにしております😆

**Comment by hashrock** [comment]
下記２箇所にて同じものを稼働させました。

- https://hashrock.github.io/md2sb-online/
- https://md2sb-online.netlify.com/

管理の簡易化と、古いほうがGoogleで上位になっているため、GitHub Pages側をメインにしていきます。
Netlify側はなにかあるまで放っておきますが、管理が面倒になってきたら削除するかもしれません。
